# Generated by Django 4.0.10 on 2023-05-20 09:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jenis_tanaman', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kebun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_kebun', models.CharField(max_length=50, unique=True)),
                ('deskripsi', models.CharField(max_length=100)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('alamat', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('id_akun', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('id_jenis_tanaman', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jenis_tanaman.jenistanaman')),
            ],
            options={
                'db_table': 'kebun',
            },
        ),
    ]
