# Generated by Django 4.0.10 on 2023-05-27 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kebun', '0002_kebundisematkan'),
    ]

    operations = [
        migrations.DeleteModel(
            name='KebunDisematkan',
        ),
    ]
