# Generated by Django 4.0.10 on 2023-05-27 04:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kebun', '0003_delete_kebundisematkan'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataKebun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ph', models.FloatField()),
                ('temperatur', models.FloatField()),
                ('tds', models.FloatField()),
                ('intensitas_cahaya', models.FloatField()),
                ('kelembapan', models.FloatField()),
                ('hasil_rekomendasi', models.CharField(blank=True, max_length=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('id_kebun', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kebun.kebun')),
            ],
            options={
                'db_table': 'data_kebun',
            },
        ),
    ]
