# Generated by Django 4.0.10 on 2023-05-27 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kebun', '0005_notifikasi_detailkirimnotifikasi'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detailkirimnotifikasi',
            name='batas_parameter',
        ),
        migrations.RemoveField(
            model_name='detailkirimnotifikasi',
            name='parameter',
        ),
        migrations.AddField(
            model_name='detailkirimnotifikasi',
            name='pesan',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
