# Generated by Django 4.0.10 on 2023-05-22 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_kebun', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datakebun',
            name='hasil_rekomendasi',
            field=models.CharField(blank=True, max_length=2),
        ),
    ]
