# Generated by Django 4.0.10 on 2023-05-24 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_kebun', '0002_alter_datakebun_hasil_rekomendasi'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datakebun',
            name='ec',
        ),
    ]
