# Generated by Django 4.0.10 on 2023-06-21 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jenis_tanaman', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jenistanaman',
            name='foto',
            field=models.ImageField(blank=True, upload_to='jenis-tanaman/foto/'),
        ),
        migrations.AlterField(
            model_name='jenistanaman',
            name='model',
            field=models.FileField(upload_to='jenis-tanaman/model/'),
        ),
    ]
