# Generated by Django 4.0.10 on 2023-05-13 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akun', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='akun',
            name='foto_profil',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
