# Generated by Django 4.0.10 on 2023-05-13 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('akun', '0002_alter_akun_foto_profil'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='akun',
            table='akun',
        ),
    ]
