# Generated by Django 4.0.10 on 2023-05-14 14:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('akun', '0003_alter_akun_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='KodeVerifikasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode', models.CharField(max_length=5)),
                ('waktu_kirim', models.DateTimeField()),
                ('waktu_kadaluarsa', models.DateTimeField()),
                ('jumlah_kirim', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('id_akun', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'kode_verifikasi',
            },
        ),
    ]
