# Generated by Django 4.0.10 on 2023-05-20 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akun', '0004_kodeverifikasi'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kodeverifikasi',
            name='jumlah_kirim',
        ),
        migrations.AddField(
            model_name='kodeverifikasi',
            name='nomor_whatsapp',
            field=models.CharField(default='0', max_length=15),
        ),
    ]
