# Generated by Django 4.0.10 on 2023-05-29 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('akun', '0005_remove_kodeverifikasi_jumlah_kirim_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kodeverifikasi',
            old_name='waktu_kadaluarsa',
            new_name='waktu_kedaluwarsa',
        ),
    ]
