# Generated by Django 4.0.10 on 2023-05-30 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akun', '0006_rename_waktu_kadaluarsa_kodeverifikasi_waktu_kedaluwarsa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='akun',
            name='nama_pengguna',
            field=models.CharField(max_length=50),
        ),
    ]
