# Generated by Django 4.0.10 on 2023-06-20 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akun', '0007_alter_akun_nama_pengguna'),
    ]

    operations = [
        migrations.AlterField(
            model_name='akun',
            name='foto_profil',
            field=models.ImageField(blank=True, upload_to='akun/foto_profil/'),
        ),
    ]
